---
label: default
hide_body: false
fields:
- name: title
  default: ''
  label: Title
  hidden: false
  type: text
- name: date
  default: ''
  label: Date
  hidden: false
  type: datetime
- name: tags
  default:
  - x
  - y
  label: Tags
  hidden: false
  type: tag_list
- name: categories
  default:
  - x
  - y
  label: Categories
  hidden: false
  type: tag_list
- name: banner
  default: ''
  label: Banner
  hidden: false
  type: file
pages:
- content/communications/agm---october-24,-2018-at-600pm.md
- content/communications/annual-report-2018.md
